In [2]:
import numpy as np 
import pandas as pd 

## Light Data Exploration

In [3]:
data = pd.read_csv("../data/clean_weather.csv")
data.head(10)

Unnamed: 0  tmax  tmin  rain  tmax_tomorrow
0  1970-01-01  60.0  35.0  0.00           52.0
1  1970-01-02  52.0  39.0  0.00           52.0
2  1970-01-03  52.0  35.0  0.00           53.0
3  1970-01-04  53.0  36.0  0.00           52.0
4  1970-01-05  52.0  35.0  0.00           50.0
5  1970-01-06  50.0  38.0  0.00           52.0
6  1970-01-07  52.0  43.0  0.00           56.0
7  1970-01-08  56.0  49.0  0.24           54.0
8  1970-01-09  54.0  50.0  0.40           57.0
9  1970-01-10  57.0  50.0  0.00           57.0

In [4]:
data.describe()

tmax          tmin          rain  tmax_tomorrow
count  13498.000000  13495.000000  13228.000000   13498.000000
mean      66.052230     50.430678      0.046302      66.052526
std        8.321769      6.785798      0.181533       8.321625
min       38.000000      1.000000      0.000000      38.000000
25%       60.000000     46.000000      0.000000      60.000000
50%       66.000000     51.000000      0.000000      66.000000
75%       71.000000     56.000000      0.000000      71.000000
max      122.000000     69.000000      3.580000     122.000000

In [5]:
data = data.ffill()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13509 entries, 0 to 13508
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Unnamed: 0     13509 non-null  object 
 1   tmax           13509 non-null  float64
 2   tmin           13509 non-null  float64
 3   rain           13509 non-null  float64
 4   tmax_tomorrow  13509 non-null  float64
dtypes: float64(4), object(1)
memory usage: 527.8+ KB


## Creating a RNN

In [6]:
np.random.seed(0)

i_weight = np.random.rand(1,2)
h_weight = np.random.rand(2,2)
o_weight = np.random.rand(2,1)

# Getting the pandas data frame with column tmax, getting the last 3 values of the column, coverting to an numpy array. 
temps = data['tmax'].tail(3).to_numpy() 
temps

array([66., 70., 62.])

In [7]:
#reshape the values into single matricies. 

x0 = temps[0].reshape(1,1)
x1 = temps[1].reshape(1,1)
x2 = temps[2].reshape(1,1)

x0

array([[66.]])

In [8]:
# time step 0
xi_0 = x0 @ i_weight 
xi_0

array([[36.22169126, 47.20249818]])

In [9]:
# ReLU Activation Function 
xh_0 = np.maximum(0, xi_0) 
xh_0

array([[36.22169126, 47.20249818]])

In [10]:
xo_0 = xh_0 @ o_weight 
xo_0


array([[57.94406231]])

In [11]:
# time step 1 
xi_1 = x1 @ i_weight 

xh = xh_0 @ h_weight 

# implemented an activation functionon on top of XH and XI. 
xh_1 = np.maximum(0, xh + xi_1)
xo_1 = xh_1

In [12]:
xo_1 = xh_1 @ o_weight

In [13]:
xo_1

array([[124.54916092]])

In [14]:
# time step 2 

xi_2 = x2 @ i_weight 
xh = xh_1 @ h_weight 
xh_2 = np.maximum(0, xh + xi_2) 
xo_2 = xh_2 @ o_weight 
xo_2


array([[190.94853131]])

In [15]:
# Calculating the Gradient is just the partial derivative of the loss function with respect to the parameter/s. 

xh_2 


array([[124.88411227, 152.84252918]])